### ISSUE TITLE
dwebsocket，如果有一台电脑的两个不同浏览器同时连服务器，被视为一个连接么？

### ISSUE THREAD

**Issue by kingctan** [duanhongyi/dwebsocket#1]
dwebsocket，如果有一台电脑的两个不同浏览器同时连服务器，被视为一个连接么？

**Comment by liyumeng** [comment]
@kingctan 每一次HTTP request都会建立一个新的TCP连接，websocket也一样。所以即使是同一个浏览器发送了多次HTTP request也都是不同的连接。只有调用js中WebSocket对象的send方法发送的数据，才会进行websocket的传输。不知道你说的“视为一个连接”是不是指的这个。而因为不同的页面不能共享js中WebSocket的对象，所以也就不视为一个连接。

**Comment by duanhongyi** [comment]
这同socket的性质是一样的。
