### ISSUE TITLE
基于virtualhost方式部署，在 self.request.META 中无法获socket，

### ISSUE THREAD

**Issue by doscho** [duanhongyi/dwebsocket#10]
dwebsocket 加入到 django项目，在开发服务器运行环境下没有问题。
但在httpd上，基于virtualhost方式部署，在 self.request.META 中无法获socket， wsgi_input的值是 'wsgi.input': <mod_wsgi.Input object at 0x7f85bf5f0230>
如何解决？谢谢！

**Comment by duanhongyi** [comment]
@doscho httpd目前并不支持，可以写自定义的backends解决这个问题。
