### ISSUE TITLE
客户端频繁向服务端发送大量小数据时发生数据截断

### ISSUE THREAD

**Issue by zhangdong046** [duanhongyi/dwebsocket#11]
经验证，客户端频繁向服务端发送大量小数据是发生数据截断：
{"func":"search","args":["xls_202.py","金","1","0","1","t0"],"sid":"s1","cid":"c5771601425"}
{"func":"search","args":["xls_202.py","金","1","0","1","t1"],"sid":"s2","cid":"c5771601425"}
...
{"func":"search","args":["xls_202.py","金","1","0","1","t1298"],"sid":"s1297","cid":"c5771601425"}
{"func":"search","args":["xls_202.py","金","1","0","1","t1299"],"sid":"s1298","cid":"c5771601425"}
{"func":"search","args":["xls_202.py","金","1","0","1","t1300"],"sid":"s12
然后socket连接自动断开，报错:
error: [Errno 9] Bad file descriptor
奇怪的是，每次尝试都是在这里断开，但是前端发送数据确实是完整的，怀疑后端接受数据累积一定长度后就会在recv_buf中截数据出错，导致后续socket断开。

**Comment by zhangdong046** [comment]
在前端使用一个for循环空发该json字符串，发送到1000多个时候，在固定位置出错。

**Comment by zhangdong046** [comment]
问题定位在了读取buf数据上，好像频繁发送数据时，
以2位长度解析sock的buf包头时会解析出错误的结果。

**Comment by duanhongyi** [comment]
@zhangdong046  谢谢反馈，我关注一下这个问题。

**Comment by duanhongyi** [comment]
@zhangdong046 

能否说明一下部署的环境？

**Comment by zhangdong046** [comment]
这个问题已经解决了，感觉应该不是你的库的问题，
应该是底层socket传输处理不了多次成批数据

**Comment by duanhongyi** [comment]
@zhangdong046 

OK
