### ISSUE TITLE
run with uwsgi report error

### ISSUE THREAD

**Issue by duzuyong** [duanhongyi/dwebsocket#18]
I use uwsgi to run my web,
add  WEBSOCKET_FACTORY_CLASS = 'dwebsocket.backends.uwsgi.factory.uWsgiWebSocketFactory' to settings.py

when I run , I have a error  

 File "/Users/admin/.virtualenvs/env_jd1.8.3/lib/python2.7/site-packages/dwebsocket/backends/uwsgi/factory.py", line 1, in <module>
    import uwsgi
ImportError: No module named uwsgi

**Comment by duanhongyi** [comment]
@duzuyong 

pip install uwsgi

**Comment by duzuyong** [comment]
![image](https://cloud.githubusercontent.com/assets/236250/19507357/f02d729c-9604-11e6-94b3-5cd9be336cad.png)

I  install uwsgi

**Comment by duanhongyi** [comment]
@duzuyong 
mac系统？mac不能pip，需要编译安装。
