### ISSUE TITLE
error: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by jumpserver** [duanhongyi/dwebsocket#2]
django version 1.6 python version 2.6.6
I have do this
1. setting.py add 'dwebsocket.middleware.WebSocketMiddleware',
2. function 
from dwebsocket import accept_websocket
@accept_websocket
def echo_once(request):
    if not request.is_websocket():
        message = 'hello'
        return HttpResponse(message)
    else:
        message = 'Hello world'
        request.websocket.send(message)
3. url.py add

I use console to connect this websocket

socket = var WebSocket("ws://192.168.40.140/echo_once/")
console log error:
WebSocket connection to 'ws://192.168.40.140/echo_once/' failed: One or more reserved bits are on: reserved1 = 1, reserved2 = 0, reserved3 = 0

Server error log:
Exception happened during processing of request from ('192.168.40.1', 58528)
Traceback (most recent call last):
  File "/usr/lib64/python2.6/SocketServer.py", line 570, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.6/SocketServer.py", line 332, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.6/site-packages/django/core/servers/basehttp.py", line 126, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "/usr/lib64/python2.6/SocketServer.py", line 628, in **init**
    self.finish()
  File "/usr/lib64/python2.6/SocketServer.py", line 671, in finish
    self.wfile.flush()
  File "/usr/lib64/python2.6/socket.py", line 303, in flush
    self._sock.sendall(buffer(data, write_offset, buffer_size))
error: [Errno 9] Bad file descriptor

**Comment by duanhongyi** [comment]
@ibuler 

use gevent or eventlet?

**Comment by jumpserver** [comment]
may be genvent , i try again with virtualenv it's ok, thanks!  Are you a chinese (from your nickname)?

**Comment by duanhongyi** [comment]
@ibuler 

是的，我的名字叫段洪义。

**Comment by jumpserver** [comment]
最近写了一个项目叫 Jumpserver -- http://github.com/ibuler/jumpserver 想用websocket实现一些功能，发现了你的项目，刚才测试没有问题，再学习一下！

**Comment by pang-w** [comment]
你俩为什么说英文 - -！

尝试了一下，非常好用的模块，感觉这个模块没有推广起来。
