### ISSUE TITLE
请问dwebsocket的支持ssl访问吗

### ISSUE THREAD

**Issue by JeffGannon** [duanhongyi/dwebsocket#27]
我在nginx里面配置了ssl,但是访问的时候报400错误

**Comment by imtiantian** [comment]
同问

**Comment by MojyFantasy** [comment]
同问

**Comment by MojyFantasy** [comment]
请问楼上解决了吗？

**Comment by imtiantian** [comment]
还没，目前能握手成功了，但发不了消息，发送消息时自动断开了socket连接

**Comment by imtiantian** [comment]
http://uwsgi-docs-zh.readthedocs.io/zh_CN/latest/WebSockets.html

**Comment by JaysenLeo** [comment]
如果我一个Django项目下既有websocket模块又有短链接，请问uwsgi的请求指令同样按websocket的开启方式么？？？

**Comment by chengxj** [comment]
ssl下使用wss连接
