### ISSUE TITLE
it seems not work in python3

### ISSUE THREAD

**Issue by wuxie2015** [duanhongyi/dwebsocket#33]
when I was using python 3.6 it seems not work , it said websocket has been closed

**Comment by duanhongyi** [comment]
linux? windows?

**Comment by wuxie2015** [comment]
Linux, seems you are Chinese,let'speak mother tongue
我在linux下用的python3.6
好像是在middleware的process_response里面的这句  if request.is_websocket():request.websocket.close()这关闭的，我注释掉后就不会再关闭了，可是websocket走的明明是socket，为什么会经过这个函数呢？百思不得其解
另外我觉得超时关闭socket应该加入到这个里面的

**Comment by wuxie2015** [comment]
而且你那个protocol.can_read()里面的select改成epoll会不会性能上升很多呢

**Comment by duanhongyi** [comment]
我一般会使用gevent或者eventlet做patch，所以正常编码即可。

**Comment by duanhongyi** [comment]
如果觉得哪里有改进的空间可以提交patch
