### ISSUE TITLE
该dwebsocket无法发送图像帧的字节数据？请问源码protocols.py该如何修改？

### ISSUE THREAD

**Issue by JamesZhan107** [duanhongyi/dwebsocket#37]
我现在想发送的数据是图像帧的字节数据，所以应该是二进制。如果直接运行，浏览器就会将数据按照UTF-8解码而报错了。注意到opcode，需要为转成二进制后是10000010。

**Comment by StarIsFalling** [comment]
请问这个问题解决了吗？如何解决的？我现在也卡在这。

**Comment by StarIsFalling** [comment]
找到了，websocket.py中:
def send(self,message)    改为     def send(self,message,binary=False)，
    return self.protocol.write(message)   改为    self.protocol.write(message,binary)

**Comment by wakingking77** [comment]
> 找到了，websocket.py中:
> def send(self,message) 改为 def send(self,message,binary=False)，
> return self.protocol.write(message) 改为 self.protocol.write(message,binary)

你好，按照你的方法，我没找到return self.protocol.write(message)，send函数里根本就没有return啊，你后来就是通过修改源码解决的吗，可以传送二进制数据了？数组可以吗？

**Comment by StarIsFalling** [comment]
> 你好，按照你的方法，我没找到return self.protocol.write(message)，send函数里根本就没有return啊，你后来就是通过修改源码解决的吗，可以传送二进制数据了？数组可以吗？

不好意思，打错了一点点。是修改源码的。在dwebsocket/backends/default/websocket.py中，源代码是这样的:
    def send(self, message):
        '''
        Send a message to the client. *message* should be convertable to a
        string; unicode objects should be encodable as utf-8.
        '''
        if not self.closed:
            self.protocol.write(message)
我修改后的:
    def send(self, message, binary=False):
        '''
        Send a message to the client. *message* should be convertable to a
        string; unicode objects should be encodable as utf-8.
        '''
        if not self.closed:
            self.protocol.write(message, binary)
没有return。而调用的时候记得采用为request.websocket.send(data,True)，比原版的输入参数多个True。


可以传送二进制数据，因为我这边数据是由c发送过来的，所以肯定是bytes。而js接收的时候用arraybuffer接收

**Comment by wakingking77** [comment]
> 
> 
> > 你好，按照你的方法，我没找到return self.protocol.write(message)，send函数里根本就没有return啊，你后来就是通过修改源码解决的吗，可以传送二进制数据了？数组可以吗？
> 
> 不好意思，打错了一点点。是修改源码的。在dwebsocket/backends/default/websocket.py中，源代码是这样的:
> def send(self, message):
> '''
> Send a message to the client. _message_ should be convertable to a
> string; unicode objects should be encodable as utf-8.
> '''
> if not self.closed:
> self.protocol.write(message)
> 我修改后的:
> def send(self, message, binary=False):
> '''
> Send a message to the client. _message_ should be convertable to a
> string; unicode objects should be encodable as utf-8.
> '''
> if not self.closed:
> self.protocol.write(message, binary)
> 没有return。而调用的时候记得采用为request.websocket.send(data,True)，比原版的输入参数多个True。
> 
> 可以传送二进制数据，因为我这边数据是由c发送过来的，所以肯定是bytes。而js接收的时候用arraybuffer接收

非常感谢你的详细回答，太感谢了！
