### ISSUE TITLE
使用python2.7, send时候抛出异常问题

### ISSUE THREAD

**Issue by liushu777** [duanhongyi/dwebsocket#38]
修改 dwebsocket/backends/default/protocols.py

data = bytes(data, 'utf-8')   ==>> data = bytes(data)

**Comment by legolas-zeng** [comment]
我也是遇到这个问题，请问您是怎么解决的？ @liushu777

**Comment by liushu777** [comment]
将dwebsocket 安装代码中
修改 dwebsocket/backends/default/protocols.py

data = bytes(data, 'utf-8') ==>> data = bytes(data)

然后重装

也可以直接去安装好的目录中修改
Python的bytes 没有第二个参数





| |
刘树
|
|
邮箱：yinheshanxing@163.com
|

签名由 网易邮箱大师 定制

在2018年11月14日 11:05，legolas-zeng 写道：

我也是遇到这个问题，请问您是怎么解决的？ @liushu777

**Comment by legolas-zeng** [comment]
多谢多谢，我自己改了没有重装，然后调用的时候用的又是用的原来的没改的，搞了好久，多谢了。 @liushu777
