### ISSUE TITLE
failed: Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by mo0feng** [duanhongyi/dwebsocket#4]
failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by mo0feng** [comment]
Django Version 1.7.8

**Comment by duanhongyi** [comment]
@mo0feng 
使用中间件是gevent、eventlet还是uwsgi?

**Comment by duanhongyi** [comment]
@mo0feng 

应该是WEBSOCKET_FACTORY_CLASS配置引起，建议详细阅读文档。关闭长时间未回复的问题。
