### ISSUE TITLE
uwsgi支持问题

### ISSUE THREAD

**Issue by nixiaoya** [duanhongyi/dwebsocket#5]
我现在已经用了uwsgi起了一个项目，想在该项目下增加即时通讯的功能，是需要在已有uwsgi的基础上，同时再起一个uwsgi吗？这样一个项目跑了两个uwsgi。望解答

**Comment by duanhongyi** [comment]
@nixiaoya 

一般情况长连接的进程是单独部署的，有利于资源的优化配置。
