### ISSUE TITLE
Django2.1.5中出现Bad Request错误，退回Django2.1.4后正常

### ISSUE THREAD

**Issue by editBug** [duanhongyi/dwebsocket#53]
Django2.1.5中出现Bad Request错误，退回Django2.1.4后正常。
请求views中处理websocket的函数时，出现Bad Request错误，更换Django版本为2.1.4后请求得到正常响应。

**Comment by sxwxs** [comment]
https://github.com/duanhongyi/dwebsocket/pull/56
这里修复了
