### ISSUE TITLE
请问支持django2.2吗 

### ISSUE THREAD

**Issue by hanfeicode** [duanhongyi/dwebsocket#55]
请问支持django2.2吗

**Comment by zhangaoqiang** [comment]
不支持

**Comment by Creling** [comment]
非常简洁的插件，但是很可惜不支持2.2啊，作者有计划对新版本django进行适配么

**Comment by duanhongyi** [comment]
@zhangaoqiang @Creling 这周有计划。

**Comment by Creling** [comment]
很高兴得知这一点

**Comment by zxj17815** [comment]
当一个视图在使用websocket的时候其他的普通视图是不能请求的吗

**Comment by duanhongyi** [comment]
websocket和普通视图不能共存，二者只能选其一，但是可以延迟决定，使用accept_websocket

**Comment by UfSkywalker** [comment]
> websocket和普通视图不能共存，二者只能选其一，但是可以延迟决定，使用accept_websocket

那么一个websocket要建立一个长连接呢？其他的http请求都会阻塞吗？

**Comment by UfSkywalker** [comment]
我现在遇到的问题是。当一个websocket在调用websocket.read()的时候发生了阻塞。然后所有的请求都阻塞了。
