### ISSUE TITLE
How to close websocket connection gracefully from the dwebsocket server

### ISSUE THREAD

**Issue by encodingl** [duanhongyi/dwebsocket#57]
When closed the websocket from the client，the server reports error as follows：
ERROR Internal Server Error: /websocketUrl/
........
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

So Could you tell me  How to close websocket connection gracefully from the dwebsocket server, 3ks
I don't find a api from your dwebsocket README

**Comment by hsh0107** [comment]
same question as you say abouve..............................

**Comment by hsh0107** [comment]
I've met the same problem as you say above

**Comment by FengJun1206** [comment]
I use Websocket.is_closed () to determine whether the websocket is disconnected and always returns False. I want to actively disconnect from the backend. What should I do? 3ks

**Comment by duanhongyi** [comment]
It usually turns off automatically

**Comment by YuaXan** [comment]
You can try use Websocket.close() of function to close websocket.

**Comment by AlitaIcon** [comment]
`request.websocket.protocol.close()`
