### ISSUE TITLE
django got ConnectionAbortedError after  browser call ws.close()

### ISSUE THREAD

**Issue by qi7chen** [duanhongyi/dwebsocket#61]
server environment: Windows 10, Python 3.7, Django 2.1.7, dwebsocket 0.5.12

this is my server code, accept websocket request and read/write messages

```python
@require_websocket
def websocket_test(request):
    ws = request.websocket
    print(ws, 'connected')
    try:
        while not ws.is_closed():
            message = ws.wait(30.0)
            if message is None:
                print('close', ws)
                ws.close()
            else:
                print(message)
                ws.send(message)
    except Exception as e:
        print(e.message)
```

and this is my browser js code, connect to server and write/read some messages, and close:

```javascript
        let counter = 0;
        let timer = null;
        let ws = new WebSocket("ws://localhost:8000/polls/ws")
        let data = 'hello,kitty';
        ws.onopen = function(event) {
            console.log('ws connected', event);
            ws.send(data)

            timer = setInterval(function() {
                ws.send(data)
            }, 3500)
        }

        ws.onmessage = function(event) {
            console.log(event);
            counter += 1;
            if (counter == 10) {
                ws.close();
            }
        }

        ws.onclose = function(event) {
            console.log(event);   
            if (timer) {
                clearInterval(timer);
                timer = null;
            }
        }
```
and if the brower call `ws.close()` after send and recv some data, server will got this error message:

```bash
Exception happened during processing of request from ('127.0.0.1', 52703)
Traceback (most recent call last):
  File "D:\App\Python\Python37\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\App\Python\Python37\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\App\Python\Python37\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "D:\App\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "D:\App\Python\Python37\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\App\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053]
```

I also tested under Linux platform(CentOS 7, Python 3.6.8), and this error message didn't appear, this is Windows-only issue.

**Comment by EroData** [comment]
I supose I GOT the same problem! I didn't use the "try...except..." structure, and my terminal GIVES me the following information:

`AttributeError: 'DefaultWebSocket' object has no attribute 'is_closed'`

This is weird while the author wirtes it clearly we can use it.

**Comment by EroData** [comment]
Solution， the is_closed() function didn't work.
After check the source code between the author's code on github and  code locally of dwebsocket, I figure why it said "*** has no attribute 'is_closed"
![图片](https://user-images.githubusercontent.com/26847296/76865476-bee42b80-689d-11ea-986d-6955ace4d113.png)
because in your local code, in all three of files, the author delete the is_closed() function.
So that's why it didn't work.
However, when you add 
```
def is_closed(self):
        return self.server_terminated or self.client_terminated
```
in backends/default/protocols.py,  add
```
def is_closed(self):
        return self.closed or self.protocol.is_closed()
```
in backends/default/websocket.py, and add
```
def is_closed(self):
        raise NotImplementedError
```
in websocket.py.
Still, it didn't work, when the client use close()function, the server didn't notice and is_closed() returns you a True value.
