### ISSUE TITLE
dwebsocket如何设置默认无消息断开时间，如何在apache上部署项目使websocket生效？

### ISSUE THREAD

**Issue by zzkxcdm** [duanhongyi/dwebsocket#7]
我在django项目下使用了dwebsocket，按照example使用accept_websocket写了个接收websocket的方法。使用django的默认启动方法启动项目，python manage.py runserver，
但是网页如果没有发送消息就差不多每隔30s会断开websocket连接，后台报错：
## [29/Oct/2015 17:37:27]"GET /websocketserver HTTP/1.1" 500 59

Exception happened during processing of request from ('10.245.138.204', 65063)
Traceback (most recent call last):
  File "C:\Python27\lib\SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Python27\lib\SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Python27\lib\site-packages\django\core\servers\basehttp.py", line 102
, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "C:\Python27\lib\SocketServer.py", line 657, in **init**
    self.finish()
  File "C:\Python27\lib\SocketServer.py", line 716, in finish
    self.wfile.close()
  File "C:\Python27\lib\socket.py", line 283, in close
    self.flush()
  File "C:\Python27\lib\socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
## error: [Errno 10038]

请问下这个断开的时间是在哪里可以设置吗？
还有，我想将该django项目使用apache部署到服务器，但是无论如何都无法连接上websocket，还是只能在服务器上使用runserver才能连接上，请问下如何将该项目部署到apache呢，谢谢。

**Comment by duanhongyi** [comment]
@zzkxcdm  

1、断开时间问题，需要在客户端每隔固定时间发送心跳包。即socket的ping协议。超时时间不同的启动方法有不同的设置方法，比如说gunicore使用的便是timeout。

2、apache必须支持websocket才能使用，目前nginx支持反向代理websocket，详见：http://nginx.com/news/nginx-websockets.html

3、不建议在windows下使用，在linux下使用epoll（需要gevent/eventlet）可以做到单个进程最少持有15w个连接，windows下尚未在生产环境中使用。

**Comment by zzkxcdm** [comment]
谢谢，回过头再研究下nginx和心跳包。

**Comment by zzkxcdm** [comment]
再请问下上面所写的报错信息是怎么一回事呢，使用你自带的example也会出现这样的报错。
在window下安装cygwin模拟unix环境，也会报错，但信息有点不同：
Exception happened during processing of request from ('127.0.0.1', 5027)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/site-packages/Django-1.8.4-py2.7.egg/django/core/servers/basehttp.py", line 102, in **init**
    super(WSGIRequestHandler, self).**init**(_args, *_kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in **init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 9] Bad file descriptor

**Comment by zzkxcdm** [comment]
下午使用nginx进行部署，使用fcgi进行连接，启动nginx后，再运行
python manage.py runfcgi host=127.0.0.1 port=8001 protocol=fcgi method=threaded。
现在已经可以访问到我部署的django站点，但是还是无法进行websocket连接。
nginx配置如下：
server {
        listen       8000;
        server_name  localhost;
        location ~ ^/ {
            # host and port to fastcgi server
            fastcgi_pass 127.0.0.1:8001;
            fastcgi_param PATH_INFO $fastcgi_script_name;
            fastcgi_param REQUEST_METHOD $request_method;
            fastcgi_param QUERY_STRING $query_string;
            fastcgi_param SERVER_NAME $server_name;
            fastcgi_param SERVER_PORT $server_port;
            fastcgi_param SERVER_PROTOCOL $server_protocol;
            fastcgi_param CONTENT_TYPE $content_type;
            fastcgi_param CONTENT_LENGTH $content_length;
            fastcgi_pass_header Authorization;
            fastcgi_intercept_errors off;  
        }
在网上找到websocket的反向代理设置如下，将以下语句添加到server下，但还是无法连接。
           location / {
        proxy_pass http://127.0.0.1:8000/websocketserver;
        proxy_redirect off;
                #proxy_set_header X-Real-IP $remote_addr;
                #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                #proxy_set_header X-NginX-Proxy true;
               proxy_http_version 1.1;
               proxy_set_header Upgrade $http_upgrade;
               proxy_set_header Connection "upgrade";
        }
在这里怎么修改设置都无法连接，我前台web页面是通过
new WebSocket("ws://127.0.0.1:8000/websocketserver");进行连接的。
@accept_websocket
def websocketserver(request):
    if request.is_websocket():
        clientlist.append(request.websocket)
        for message in request.websocket:
            if message == '~H#C~':
                request.websocket.send('~H#S~')
            else:
                if request.META.has_key('HTTP_X_FORWARDED_FOR'):
                    ip = request.META['HTTP_X_FORWARDED_FOR'] 
                else:
                    ip = request.META['REMOTE_ADDR'] 
                request.websocket.send(ip)
请问下nginx的反向代理设置应该如何设置呢， 真心谢谢。

**Comment by Hugh-wong** [comment]
楼上，fastcgi应该是不支持的吧，我这边配置的gunicorn，非常Easy。

**Comment by zzkxcdm** [comment]
@Hugh-wong 这个应该是unix系统下的吧，可惜我是的服务器是在window下的，好难找资料。
pip装了gunicorn这个module，可是接下来又少了ffi模块，找不到怎么装了

**Comment by Hugh-wong** [comment]
嗯，用的ubuntu。
windows下确实不支持gunicorn，但是有uwsgi。

**Comment by zzkxcdm** [comment]
@Hugh-wong 查了下uwsgi在window下也是不能安装的啊，真是不知道window下能使用弄，真是越来越觉得windows没什么用了

**Comment by duanhongyi** [comment]
@Hugh-wong 
@zzkxcdm 

fastcgi确实不支持websocket；从生产环境上来看，最佳组合是: gunicorn(gevent/eventlet) + nginx；

另外windows下可以使用虚拟机或者docker来部署。

**Comment by zzkxcdm** [comment]
@duanhongyi 现在在ubuntu用nginx和uwsgi进行部署成功了，再请问一个问题：在前台网页可以使用ws.close()方法断开连接，但在服务器上如何主动断开与前台网页的连接呢？看了你的说明，好像没有这方面的介绍。

还有另外一个问题：request.websocket有没有一个标识符呢，可以让我保存到数据库中再选择对应连接的客户端进行发送。

**Comment by duanhongyi** [comment]
@zzkxcdm 

一、直接request.websocket.close()即可，参见websocket.close(self, code=None, reason=None)函数。

二、这个属于业务范畴，你这个需求可能在推送业务中常用，提供一个实现思路。
1、为每个连接进行编号。比如说:  ws://db.channel.com/pull_channel/1111111111，其中1111111111为管道id。

2、将这个编号同对应的websocket对象在内存中关联（可使用dict）。

3、那么就存在另外一个发送URL，对应的是：http://db.channel.com/send_channel/1111111111

4、发送的时候找到对应编号的对应的websocket对象即可。
