### ISSUE TITLE
在django端,有没有events可以使用?

### ISSUE THREAD

**Issue by SparksFyz** [duanhongyi/dwebsocket#8]
还有数据只支持字符串是吗?

**Comment by duanhongyi** [comment]
@SparksFyz 

events说的是事件吗？还是指某些backends?

dwebsocket设计原则是使用协程代替事件回调；在协程的模型里不需要使用事件机制。目前dwebsocket支持的后端有：gevent/eventlent/gunicorn，这三个后端均在生产环境中使用，效果最好的是gevent，单个进程可以支持20w个长连接。

一般情况websocket不太适合大量二进制数据，适合做长连接模型。如果是大批量二进制传输，推荐用传统http协议。少量二进制数据可以考虑使用base64编码。
