### ISSUE TITLE
请问如何查询Django当前使用的后端？我使用Django1.9开发的工程，中途使用pip安装的dwebsocket0.4.2，出现了以下trace

### ISSUE THREAD

**Issue by Rafy-zz** [duanhongyi/dwebsocket#9]
我看到README里面提到，dwebsocket默认支持Django的开发环境：
`Django develop server, eventlent, gevent, gunicore are supported by default.`

我是用Django1.9开发的工程，用到一半需要使用websocket，然后就来到了这里，使用pip安装的dwebsocket，然后在代码里使用websocket，但是发现只要客户端一发起websocket连接请求，服务端出现以下trace：
![abc](https://cloud.githubusercontent.com/assets/1998800/13737049/336a0d5c-e9f5-11e5-9797-3b5eadbf0671.png)

我看到issue里面提到了很多这种trace，作者都是问是否使用了gevent之类的，当前使用的backend是什么如何查询？我是用`python manage.py runserver 0.0.0.0:8080`启动的服务器，应该是develop server，这个不是默认就支持的吗？

备注：服务端的操作系统是debian linux

菜鸟求解答，谢谢

**Comment by duanhongyi** [comment]
@Rafy 因为目前wsgi规范中并无websocket相关规范，目前的做法实际上是一种hack的方式，目前在develop server上面还有诸多问题，比如说关闭websocket就会报这个错误，但是不影响正常的实用，这些问题我正在想办法解决。
